/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    theme: {
        extend: {
            fontFamily: {
                sans: 'Mont',
            },
        },
        colors: {
            white: '#FFFFFF',
            'white-60': '#FFFFFF99',
            'dark-blue': '#263238',
            'dark-blue-40': '#26323866',
            'dark-blue-10': '#2632381A',
            'dark-blue-3': '#26323808',
            green: '#008080',
            'green-20': '#00808033',
            'green-10': '#0080801A',
            blue: '#E8EDF7',
            'light-blue': '#F5F5F5',
            disabled: '#FFFFFF80',
            grey: '#E3E5E6',
            error: '#EB5757',
            success: '#27AE60',
        },
        screens: {
            sm: '320px',
            md: '640px',
            lg: '1600px',
        },
        fontFamily: {
            'corner-title': '',
            'link-title': '',
            h1: '',
            h2: '',
            h3: '',
            h4: '',
            'button-1': '',
            'button-2': '',
            'text-1': '',
            'text-2': '',
            'discount-text': '',
            'news-headline': '',
            'news-text': '',
            'numeric-1': '',
            'numeric-2': '',
            caption: '',
        },
    },
    plugins: [],
};
